### ISSUE TITLE
Creating parent encryption key - handle already in use

### ISSUE THREAD

**Issue by Yannik** [electrickite/luks-tpm2#16]
When trying to write to the persistent handle with `tpm2_evictcontrol -c primary.ctx 0x81000001`, the following error is produced:
```
WARNING:esys:src/tss2-esys/api/Esys_EvictControl.c:330:Esys_EvictControl_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_EvictControl.c:114:Esys_EvictControl() Esys Finish ErrorCode (0x0000014c)
ERROR: Esys_EvictControl(0x14C) - tpm:error(2.0): NV Index or persistent object already defined
ERROR: Unable to run tpm2_evictcontrol
```

I can see that this handle actually exists with `tpm2_getcap handles-persistent`, and I was able to clear it using `tpm2_evictcontrol -C o -c 0x81000001`. However, I was not really sure *what* I was deleting here. 

Is there anything that should be stored there with a fresh debian 12 (linux kernel 6.1) install? 
This is a new intel nuc with no prior os install.

**Comment by electrickite** [comment]
TPM use and configuration is often different from system to system, manufacturer to manufacturer, and OS to OS. I'm not sure what your system may be storing at that address, but you can always choose another location to store your key. Because this does not appear to be an issue with luke-tpm2, I am going to close this issue.
